name = "Keeli Company Auxillary Mod"
author = "Keeli Company Aux Team"
prefix = "BNA_KC"
mainprefix = "ORA"

[version]
path = "addons/core/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_kc.png",
    "logo_kc_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = ["*.spp", "*.spp.painter_lock", "*.psd"]

[properties]
author = "Keeli Company Aux Team"
url = "https://github.com/Outer-Rim-Armory/Aux-Mod"

[hemtt.launch.default]
workshop = [
    "2369477168", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2018593688", # ZEN ACE Compat
    "2522638637", # ACE Arsenal Extended
    "2567352444", # WBK Droids # TODO: Move assets to aux itself
    "767380317",  # Blastcore # Only used to test particle effects
]
presets = ["main"]
dlc = []
optionals = []
mission = "AuxTest.VR"
parameters = []

[hemtt.launch.full]
workshop = [
    "2369477168", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2018593688", # ZEN ACE Compat
    "1686872930", # SDT
    "2567352444", # WBK Droids # TODO: Move assets to aux itself
    "2522638637", # ACE Arsenal Extended
    "1572627279", # OPTRE First Contact
    "2915485125", # Burn 'Em
    "767380317",  # Blastcore
    "2789152015", # WBK Zombies
    "2478080991", # Scion Conflict
]
presets = ["main"]
dlc = []
optionals = ["no_burn_screams"]
mission = "AuxTest.VR"
parameters = []

[hemtt.launch.previews]
workshop = [
    "2369477168", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2018593688", # ZEN ACE Compat
    "1686872930", # SDT
    "2567352444", # WBK Droids # TODO: Move assets to aux
    "1572627279", # OPTRE First Contact
    "2915485125", # Burn 'Em
    "767380317",  # Blastcore
    "2789152015", # WBK Zombies
    "2478080991", # Scion Conflict
]
presets = ["main"]
dlc = []
optionals = []
parameters = [
    "C:\\Users\\skull\\OneDrive\\Documents\\Arma 3 - Other Profiles\\Previews\\missions\\Previews.VR\\mission.sqm",
    "-name=Previews",
]
