name = "Keeli Company Auxillary Mod"
author = "Keeli Company Aux Team"
prefix = "BNA_KC"
mainprefix = ""

[version]
path = "addons/core/script_version.hpp"
git_hash = 0
[lints.config.file_type]
options.allow_no_extension = true

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_kcKeeli.png",
    "logo_kcKeeli_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = ["*.spp", "*.spp.painter_lock", "*.psd"]

[properties]
author = "Keeli Company Aux Team"
url = "https://github.com/Outer-Rim-Armory/Aux-Mod"

[hemtt.launch.default]
workshop = [
    "463939057", # ace
    "450814997", # CBA_A3
    "3499977893", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2173635424", # 501st Aux Mod
    "1702480117", # 212th Auxiliary Assets
    "2162749089", # Legion Studios Core - Stable
    # "2522638637", # ACE Arsenal Extended
    "2567352444", # WBK Droids # TODO: Move assets to aux itself
    "2954535667", # Warmantle Armory
    "767380317", # Blastcore # Only used to test particle effects
    "2061309401", # Last Force Project
    "2291129343", # Improved Melee System
    "1393068220", # Kobra Mod Pack - Main
    "2058554822", # 3AS (Beta Test)
    "2215872933", # 3AS Terrains (Beta)
    "769440155", # Operation TREBUCHET
    "3203512867", # The Great Forge
    "2478080991", # Scion Conflict
    "3469976535", # Weapon Research and Security: Autonomous systems
    "1967740913", # Jango's Armory
    # "2605563484", # Scion Conflict Extended Arsenal
]
presets = ["main"]
dlc = []
optionals = []
mission = "AuxTest.VR"
parameters = []

[hemtt.launch.full]
extends = "default"
workshop = [
    "1572627279", # OPTRE First Contact
    "2915485125", # Burn 'Em
    "2789152015", # WBK Zombies
    "2323185592", # Lightsabers and Force
    "570118882", # No Weapon Sway
    "3328314886", # Heavy Weapon Framework
]
optionals = ["no_burn_screams"]

[hemtt.launch.previews]
extends = "full"
mission = "Previews.VR"
parameters = ["-name=Previews"]
